const countries = [
    "Afganistán",
    "Albania",
    "Alemania",
    "Andorra",
    "Angola",
    "Anguila",
    "Antigua y Barbuda",
    "Antártida",
    "Arabia Saudita",
    "Argelia",
    "Argentina",
    "Armenia",
    "Aruba",
    "Australia",
    "Austria",
    "Azerbaiyán",
    "Bahamas",
    "Bahrein",
    "Bangladesh",
    "Barbados",
    "Belice",
    "Benin",
    "Bermudas",
    "Bielorrusia",
    "Bolivia",
    "Bonaire, San Eustaquio y Saba",
    "Bosnia y Herzegovina",
    "Botswana",
    "Brasil",
    "Brunei Darussalam",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Bután",
    "Bélgica",
    "Cabo Verde",
    "Camboya",
    "Camerún",
    "Canadá",
    "Catar",
    "Chad",
    "Chile",
    "China",
    "Chipre",
    "Colombia",
    "Comoras",
    "Congo",
    "Congo (República Democrática del)",
    "Costa Rica",
    "Costa de Marfil",
    "Croacia",
    "Cuba",
    "Curaçao",
    "Dinamarca",
    "Dominica",
    "Ecuador",
    "Egipto",
    "El Salvador",
    "Emiratos Árabes Unidos",
    "Eritrea",
    "Eslovaquia",
    "Eslovenia",
    "España",
    "Estados Unidos",
    "Estonia",
    "Esuatini",
    "Etiopía",
    "Fiji",
    "Filipinas",
    "Finlandia",
    "Francia",
    "Gabón",
    "Gambia",
    "Georgia",
    "Georgia del Sur y las Islas Sandwich del Sur",
    "Ghana",
    "Gibraltar",
    "Granada",
    "Grecia",
    "Groenlandia",
    "Guadalupe",
    "Guam",
    "Guatemala",
    "Guayana Francesa",
    "Guernsey",
    "Guinea",
    "Guinea Bissau",
    "Guinea Ecuatorial",
    "Guyana",
    "Haití",
    "Heard e Islas McDonald",
    "Honduras",
    "Hong Kong",
    "Hungría",
    "India",
    "Indonesia",
    "Iraq",
    "Irlanda",
    "Irán",
    "Isla Bouvet",
    "Isla Norfolk",
    "Isla de Man",
    "Isla de Navidad",
    "Islandia",
    "Islas Caimán",
    "Islas Cocos (Keeling)",
    "Islas Cook",
    "Islas Feroe",
    "Islas Malvinas",
    "Islas Marianas del Norte",
    "Islas Marshall",
    "Islas Salomón",
    "Islas Turcas y Caicos",
    "Islas Ultramarinas Menores de los Estados Unidos",
    "Islas Vírgenes británicas",
    "Islas Vírgenes de los Estados Unidos",
    "Islas Åland",
    "Israel",
    "Italia",
    "Jamaica",
    "Japón",
    "Jersey",
    "Jordania",
    "Kazajistán",
    "Kenia",
    "Kirguistán",
    "Kiribati",
    "KosovoKuwait",
    "Lesoto",
    "Letonia",
    "Liberia",
    "Libia",
    "Liechtenstein",
    "Lituania",
    "Luxemburgo",
    "Líbano",
    "Macao",
    "Macedonia del Norte",
    "Madagascar",
    "Malasia",
    "Malaui",
    "Maldivas",
    "Malta",
    "Malí",
    "Marruecos",
    "Martinica",
    "Mauricio",
    "Mauritania",
    "Mayotte",
    "Micronesia",
    "Moldavia",
    "Mongolia",
    "Montenegro",
    "Montserrat",
    "Mozambique",
    "Myanmar",
    "México",
    "Mónaco",
    "Namibia",
    "Nauru",
    "Nepal",
    "Nicaragua",
    "Nigeria",
    "Niue",
    "Noruega",
    "Nueva Caledonia",
    "Nueva Zelanda",
    "Níger",
    "Omán",
    "Pakistán",
    "Palau",
    "Palestina",
    "Panamá",
    "Papua Nueva Guinea",
    "Paraguay",
    "Países Bajos",
    "Perú",
    "Pitcairn",
    "Polinesia Francesa",
    "Polonia",
    "Portugal",
    "Puerto Rico",
    "Reino Unido",
    "República Centroafricana",
    "República Checa",
    "República Democrática Popular de Lao",
    "República Dominicana",
    "República Popular Democrática de Corea",
    "República de Corea",
    "República Árabe Siria",
    "Reunión",
    "Ruanda",
    "Rumanía",
    "Rusia",
    "Sahara Occidental",
    "Saint Barthélemy",
    "Saint Kitts y Nevis",
    "Saint Martin (francesa)",
    "Samoa",
    "Samoa Americana",
    "San Marino",
    "San Pedro y Miquelón",
    "San Vicente y las Granadinas",
    "Santa Helena, Ascensión y Tristán de Acuña",
    "Santa Lucía",
    "Santa Sede",
    "Santo Tomé y Príncipe",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leona",
    "Singapur",
    "Sint Maarten (neerlandesa)",
    "Somalia",
    "Sri Lanka",
    "Sudáfrica",
    "Sudán",
    "Sudán del Sur",
    "Suecia",
    "Suiza",
    "Suriname",
    "Svalbard y Jan Mayen",
    "Tailandia",
    "Taiwán",
    "Tanzania",
    "Tayikistán",
    "Territorio Británico del Océano Índico",
    "Tierras Australes Francesas",
    "Timor-Leste",
    "Togo",
    "Tokelau",
    "Tonga",
    "Trinidad y Tobago",
    "Turkmenistán",
    "Turquía",
    "Tuvalu",
    "Túnez",
    "Ucrania",
    "Uganda",
    "Uruguay",
    "Uzbekistán",
    "Vanuatu",
    "Venezuela",
    "Vietnam",
    "Wallis y Futuna",
    "Yemen",
    "Yibuti",
    "Zambia",
    "Zimbabue",
];

export default countries;